import { Button } from '@chakra-ui/react';

const Home = () => {
  return (
    <div>
      <p>Hello Agile</p>
      <p>
        <Button>中文按钮</Button>
      </p>
      <p>
        <Button>中文按钮</Button>
      </p>
      <p>
        <Button>中文按钮</Button>
      </p>
      <p>
        <Button>中文按钮</Button>
      </p>
      <p>
        <Button>中文按钮</Button>
      </p>
      <p>
        <Button>中文按钮</Button>
      </p>
      <p>
        <Button>中文按钮</Button>
      </p>
      <p>
        <Button>中文按钮</Button>
      </p>
      <p>
        <button>中文按钮</button>
      </p>
      <p>
        <button>中文按钮</button>
      </p>
      <p>
        <button>中文按钮</button>
      </p>
      <p>
        <button>中文按钮</button>
      </p>
      <p>
        <button>中文按钮</button>
      </p>
      <p>
        <button>中文按钮</button>
      </p>
      <p>
        <button>中文按钮</button>
      </p>
      <p>
        <button>中文按钮</button>
      </p>
      <p>
        <button>中文按钮</button>
      </p>
      <p>
        <button>中文按钮</button>
      </p>
      <p>
        <button>中文按钮</button>
      </p>
      <p>
        <button>中文按钮</button>
      </p>
      <p>
        <button>中文按钮</button>
      </p>
      <p>
        <button>中文按钮</button>
      </p>
      <p>
        <button>中文按钮</button>
      </p>
      <p>
        <button>中文按钮</button>
      </p>
      <p>
        <button>中文按钮</button>
      </p>
      <p>
        <button>中文按钮</button>
      </p>
      <p>
        <button>中文按钮</button>
      </p>
    </div>
  );
};

export default Home;
